import { getApiKeyRecord } from "../services/api-key-service.js";
import { takeRoundRobinAccount } from "../services/account-rotation-service.js";
import { isIncognitoEnabledForOwner } from "../services/incognito-service.js";
import { getConversationId, getConversationState } from "../services/conversation-service.js";
import { collectOpenAiResponse, streamOpenAiResponse } from "../services/openai-bridge.js";
import { hasChatToolingRequest } from "../services/openai-tool-policy.js";
import { listOpenAiModels } from "../services/openai-request.js";
import { recordRequestLog } from "../services/request-log-service.js";
import { withOwnerRequestLimit } from "../services/request-limit-service.js";
import { parseJsonBody, readRequestBody, sendError, sendJson } from "../utils/http.js";
function getBearerToken(request) { const match = /^Bearer\s+(.+)$/i.exec(request.headers.authorization ?? ""); return match ? match[1].trim() : ""; }
function isModelsPath(pathname) { return pathname === "/models" || pathname === "/models/" || pathname === "/v1/models" || pathname === "/v1/models/"; }
function isChatCompletionsPath(pathname) { return pathname === "/v1/chat/completions" || pathname === "/v1/chat/completions/"; }
function resolveLimitStatus(error) { return error.code === "USER_DISABLED" ? 403 : 429; }
function handleOpenAiError(response, error) { if (error.code === "USER_DISABLED" || error.code === "REQUEST_LIMIT") { sendError(response, resolveLimitStatus(error), error.message); return true; } if (error instanceof SyntaxError) { sendError(response, 400, "Invalid JSON body"); return true; } if (error.statusCode) { sendError(response, error.statusCode, error.message); return true; } return false; }
async function handleModelsRequest(response, apiKeyRecord) { await withOwnerRequestLimit(apiKeyRecord.ownerId, async () => sendJson(response, 200, { object: "list", data: listOpenAiModels() })); }
async function handleChatCompletionsRequest(request, response, apiKeyRecord) { await withOwnerRequestLimit(apiKeyRecord.ownerId, async () => { const startedAt = Date.now(); const body = parseJsonBody(await readRequestBody(request)) ?? {}; const conversationId = getConversationId(request, body); const deleteAfterFinish = isIncognitoEnabledForOwner(apiKeyRecord.ownerId); const account = takeRoundRobinAccount(apiKeyRecord, { forceFixed: Boolean(conversationId) || hasChatToolingRequest(body) }); if (!account) { recordRequestLog({ method: "POST", path: "/v1/chat/completions", model: body.model, ownerId: apiKeyRecord.ownerId, status: 404, durationMs: Date.now() - startedAt, error: "Account not found or the Key's fixed account is unavailable" }); sendError(response, 404, "The API Key's selected DeepSeek account is unavailable. Rebind its token or switch this Key to account rotation."); return; } const stored = !deleteAfterFinish && getConversationState({ ownerId: apiKeyRecord.ownerId, apiKeyId: apiKeyRecord.id, accountId: account.id, conversationId }); const lineage = !deleteAfterFinish && conversationId ? { conversationId, ownerId: apiKeyRecord.ownerId, apiKeyId: apiKeyRecord.id, accountId: account.id, sessionId: stored?.sessionId ?? null, parentMessageId: stored?.parentMessageId ?? null } : null; try { if (body.stream) { await streamOpenAiResponse({ response, account, body, deleteAfterFinish, toolCallsEnabled: apiKeyRecord.toolCallsEnabled, lineage }); recordRequestLog({ method: "POST", path: "/v1/chat/completions", model: body.model, ownerId: apiKeyRecord.ownerId, accountId: account.id, status: 200, durationMs: Date.now() - startedAt }); return; } const payload = await collectOpenAiResponse({ account, body, deleteAfterFinish, toolCallsEnabled: apiKeyRecord.toolCallsEnabled, lineage }); sendJson(response, 200, payload); recordRequestLog({ method: "POST", path: "/v1/chat/completions", model: body.model, ownerId: apiKeyRecord.ownerId, accountId: account.id, status: 200, durationMs: Date.now() - startedAt }); } catch (error) { recordRequestLog({ method: "POST", path: "/v1/chat/completions", model: body.model, ownerId: apiKeyRecord.ownerId, accountId: account.id, status: error.statusCode ?? 500, durationMs: Date.now() - startedAt, error: error.message }); throw error; } }); }
export async function handleOpenAiRequest(request, response, url) { const apiKey = getBearerToken(request); const apiKeyRecord = apiKey ? getApiKeyRecord(apiKey) : null; if (!apiKeyRecord) { sendError(response, 401, "Invalid API key"); return true; } try { if (request.method === "GET" && isModelsPath(url.pathname)) { await handleModelsRequest(response, apiKeyRecord); return true; } if (request.method === "POST" && isChatCompletionsPath(url.pathname)) { await handleChatCompletionsRequest(request, response, apiKeyRecord); return true; } } catch (error) { if (!handleOpenAiError(response, error)) throw error; return true; } return false; }
