import { randomUUID } from "node:crypto";
import { collectCompletionContent, streamCompletionContent } from "./openai-completion-runner.js";
import { extractLatestUserImageContext } from "./openai-image-input.js";
import { formatCompletedImageToolResult, latestCompletedImageToolResult } from "./openai-image-result-finalizer.js";
import { saveConversationState } from "./conversation-service.js";
import { assertNoLegacySearchOptions, resolveOpenAiModel } from "./openai-request.js";
import { createToolSieve, extractToolAwareOutput } from "./openai-tool-sieve.js";
import { inferToolChoiceForRequest } from "./openai-tool-choice-inference.js";
import { filterToolsForRequest, IMAGE_GENERATION_TOOL_NAMES, limitImageGenerationCalls } from "./openai-tool-loop-guard.js";
import { repairToolCalls, formatRejectedToolCalls } from "./openai-tool-arguments.js";
import { buildOpenAiPrompt } from "./openai-tool-prompt.js";
import { createToolCorrectionRequest, isRequiredToolPolicy } from "./openai-tool-retry.js";
import { ensureToolChoiceSatisfied, getToolName, hasChatToolingRequest } from "./openai-tool-policy.js";
import { createTranscriptLeakRouter, splitLeakedTranscript } from "./openai-transcript-sanitizer.js";
import { createOpenAiError } from "./openai-error.js";

function createCompletionId() { return `chatcmpl_${randomUUID()}`; }
function createChatToolCalls(calls, startIndex = 0) { return calls.map((call, offset) => ({ index: startIndex + offset, id: call.id, type: "function", function: { name: call.name, arguments: call.argumentsText } })); }
function messageText(message) { if (typeof message?.content === "string") return message.content; if (!Array.isArray(message?.content)) return ""; return message.content.map((part) => part?.text ?? part?.output_text ?? part?.content ?? "").filter(Boolean).join("\n"); }
function inferToolChoice(messages, tools, suppliedChoice) { return inferToolChoiceForRequest(messages, tools, suppliedChoice); }
function continuationPrompt(messages, fullPrompt, lineage) { if (!lineage?.sessionId || !Array.isArray(messages) || !messages.length) return fullPrompt; const last = messages.at(-1); const role = String(last?.role ?? "").toLowerCase(); if (role === "user") return `USER: ${messageText(last)}\n\nASSISTANT:`; if (role === "tool" || role === "function") return `TOOL: ${messageText(last)}\n\nUSER: Answer my latest request now.\n\nASSISTANT:`; return fullPrompt; }
function resolveCompletionRequest(body, toolCallsEnabled, lineage = null) { assertNoLegacySearchOptions(body); if (!toolCallsEnabled && hasChatToolingRequest(body)) throw createOpenAiError(400, "Tool calls are disabled for this API key"); const model = resolveOpenAiModel(body?.model); const messages = body?.messages ?? []; const imageContext = extractLatestUserImageContext(messages); const refFileIds = Array.isArray(body?.ref_file_ids) ? body.ref_file_ids.filter(Boolean) : []; if ((imageContext.imageInputs.length || refFileIds.length) && model.supportsUploads === false) throw createOpenAiError(400, "Expert models do not support file or image uploads"); const tools = toolCallsEnabled ? filterToolsForRequest(body?.tools ?? [], messages) : []; const requestedToolChoice = toolCallsEnabled && tools.length ? inferToolChoice(messages, tools, body?.tool_choice) : undefined; const promptRequest = buildOpenAiPrompt({ messages, toolChoice: requestedToolChoice, tools }); return { model, messages, tools, prompt: continuationPrompt(messages, promptRequest.prompt, lineage), imageInputs: imageContext.imageInputs, imageUserText: imageContext.userText, refFileIds, toolChoicePolicy: promptRequest.toolChoicePolicy, toolNames: promptRequest.toolNames, sessionId: lineage?.sessionId, parentMessageId: lineage?.parentMessageId ?? null }; }
function formatSearchSources(searchResults = []) { const entries = searchResults.filter((item) => item?.url).slice(0, 8).map((item, index) => { const label = item.title || item.siteName || `来源 ${index + 1}`; return `${index + 1}. [${label.replaceAll("[", "［").replaceAll("]", "］")}](${item.url})`; }); return entries.length ? `\n\n**参考来源**\n${entries.join("\n")}` : ""; }
function redactSensitiveReasoning(value) { return String(value ?? "").replace(/Bearer\s+[A-Za-z0-9._~+\/-]+=*/gi, "Bearer [已隐藏]").replace(/((?:password|passwd|pwd|userToken|access[_-]?token|authorization|token_2|登录码|密码)\s*(?:is|是|为|[:=：])\s*["'“”]?)([^\s"'“”},，。；;！？!?]{4,})/gi, "$1[已隐藏]").replace(/([\"'](?:password|passwd|pwd|userToken|access_token|authorization|token_2)[\"']\s*:\s*[\"'])([^\"']+)([\"'])/gi, "$1[已隐藏]$3"); }
function createStreamingReasoningRedactor(onSafeText) { const holdBackChars = 48; let pending = ""; function emitAvailable() { if (pending.length <= holdBackChars) return; const cut = pending.length - holdBackChars; const safe = redactSensitiveReasoning(pending.slice(0, cut)); pending = pending.slice(cut); if (safe) onSafeText(safe); } return Object.freeze({ push(text) { pending += String(text ?? ""); emitAvailable(); }, flush() { if (!pending) return; const safe = redactSensitiveReasoning(pending); pending = ""; if (safe) onSafeText(safe); } }); }
function withReasoning(message, reasoningContent) { const safe = redactSensitiveReasoning(reasoningContent); return safe ? { ...message, reasoning_content: safe } : message; }
function dedupeToolCalls(calls) { const seen = new Set(); return (calls ?? []).filter((call) => { const key = `${call?.name ?? ""}\u0000${call?.argumentsText ?? ""}`; if (seen.has(key)) return false; seen.add(key); return true; }); }
function parseCollectedToolOutput(content, reasoningContent, requestOptions) { if (!requestOptions.toolNames.length) { const leak = splitLeakedTranscript(content); return { content: leak.visible, reasoningContent: `${reasoningContent}${leak.reasoning}`, toolCalls: [], rejected: [] }; } const visible = extractToolAwareOutput(content, requestOptions.toolNames); const reasoning = extractToolAwareOutput(reasoningContent, requestOptions.toolNames); const joined = extractToolAwareOutput(`${reasoningContent}${content}`, requestOptions.toolNames); const leak = splitLeakedTranscript(visible.content); const rawCalls = limitImageGenerationCalls(dedupeToolCalls([...visible.toolCalls, ...reasoning.toolCalls, ...joined.toolCalls])); const repaired = repairToolCalls({ calls: rawCalls, tools: requestOptions.tools, messages: requestOptions.messages }); const rejectionText = formatRejectedToolCalls(repaired.rejected); return { content: [leak.visible, rejectionText].filter(Boolean).join("\n\n"), reasoningContent: `${reasoning.content}${leak.reasoning}`, toolCalls: repaired.calls, rejected: repaired.rejected }; }
function parseCompletionResult(result, requestOptions) { return parseCollectedToolOutput(`${result.content}${formatSearchSources(result.searchResults)}`, result.reasoningContent, requestOptions); }
async function collectWithRequiredToolRetry({ account, deleteAfterFinish, requestOptions }) { const first = await collectCompletionContent({ account, deleteAfterFinish, requestOptions }); const firstParsed = parseCompletionResult(first, requestOptions); if (!isRequiredToolPolicy(requestOptions.toolChoicePolicy) || firstParsed.toolCalls.length) return { result: first, parsed: firstParsed }; const correctionOptions = createToolCorrectionRequest(requestOptions, first); const second = await collectCompletionContent({ account, deleteAfterFinish, requestOptions: correctionOptions }); const secondParsed = parseCompletionResult(second, requestOptions); ensureToolChoiceSatisfied(requestOptions.toolChoicePolicy, secondParsed.toolCalls); return { result: second, parsed: secondParsed }; }
function buildChatCompletionPayload(completionId, requestOptions, result, parsed = parseCompletionResult(result, requestOptions)) { ensureToolChoiceSatisfied(requestOptions.toolChoicePolicy, parsed.toolCalls); const baseMessage = { role: "assistant", content: parsed.content.length ? parsed.content : null }; if (parsed.toolCalls.length) return { id: completionId, object: "chat.completion", created: Math.floor(Date.now() / 1000), model: requestOptions.model.id, choices: [{ index: 0, finish_reason: "tool_calls", message: withReasoning({ ...baseMessage, tool_calls: createChatToolCalls(parsed.toolCalls) }, parsed.reasoningContent) }] }; return { id: completionId, object: "chat.completion", created: Math.floor(Date.now() / 1000), model: requestOptions.model.id, choices: [{ index: 0, finish_reason: "stop", message: withReasoning(baseMessage, parsed.reasoningContent) }] }; }
function buildDirectCompletionPayload(completionId, model, content) { return { id: completionId, object: "chat.completion", created: Math.floor(Date.now() / 1000), model, choices: [{ index: 0, finish_reason: "stop", message: { role: "assistant", content } }] }; }
function buildChunkPayload(completionId, model, delta, finishReason) { return { id: completionId, object: "chat.completion.chunk", created: Math.floor(Date.now() / 1000), model, choices: [finishReason ? { index: 0, delta: {}, finish_reason: finishReason } : { index: 0, delta }] }; }
function writeSseChunk(response, payload) { response.write(`data: ${JSON.stringify(payload)}\n\n`); }
function writeSseError(response, error) { response.write(`data: ${JSON.stringify({ error: { message: error?.message || "DeepSeek request failed", type: "server_error" } })}\n\n`); }
function beginSse(response) { if (!response.headersSent) { response.writeHead(200, { "cache-control": "no-cache, no-transform", connection: "keep-alive", "content-type": "text/event-stream; charset=utf-8", "x-accel-buffering": "no" }); response.flushHeaders?.(); } }
function rememberLineage(lineage, result) { if (lineage?.conversationId && result?.sessionId) saveConversationState({ ownerId: lineage.ownerId, apiKeyId: lineage.apiKeyId, accountId: lineage.accountId, conversationId: lineage.conversationId, sessionId: result.sessionId, parentMessageId: result.responseMessageId ?? lineage.parentMessageId ?? null }); }

export async function collectOpenAiResponse({ account, body, deleteAfterFinish = false, toolCallsEnabled = false, lineage = null }) { const completedImage = latestCompletedImageToolResult(body?.messages ?? []); if (completedImage) { const model = resolveOpenAiModel(body?.model); return buildDirectCompletionPayload(createCompletionId(), model.id, formatCompletedImageToolResult(completedImage)); } const requestOptions = resolveCompletionRequest(body, toolCallsEnabled, lineage); const { result, parsed } = await collectWithRequiredToolRetry({ account, deleteAfterFinish, requestOptions }); rememberLineage(lineage, result); return buildChatCompletionPayload(createCompletionId(), requestOptions, result, parsed); }

export async function streamOpenAiResponse(options) {
  const { account, body, deleteAfterFinish = false, onInvalidSession, response, toolCallsEnabled = false, lineage = null, retryInvalidSession = false } = options;
  const completionId = createCompletionId();
  const completedImage = latestCompletedImageToolResult(body?.messages ?? []);
  if (completedImage) { const model = resolveOpenAiModel(body?.model); beginSse(response); writeSseChunk(response, buildChunkPayload(completionId, model.id, { role: "assistant" })); writeSseChunk(response, buildChunkPayload(completionId, model.id, { content: formatCompletedImageToolResult(completedImage) })); writeSseChunk(response, buildChunkPayload(completionId, model.id, {}, "stop")); response.end("data: [DONE]\n\n"); return; }
  const requestOptions = resolveCompletionRequest(body, toolCallsEnabled, lineage);
  if (isRequiredToolPolicy(requestOptions.toolChoicePolicy)) {
    try {
      const { result, parsed } = await collectWithRequiredToolRetry({ account, deleteAfterFinish, requestOptions });
      beginSse(response); writeSseChunk(response, buildChunkPayload(completionId, requestOptions.model.id, { role: "assistant" })); if (parsed.content) writeSseChunk(response, buildChunkPayload(completionId, requestOptions.model.id, { content: parsed.content })); if (parsed.toolCalls.length) writeSseChunk(response, buildChunkPayload(completionId, requestOptions.model.id, { tool_calls: createChatToolCalls(parsed.toolCalls) })); rememberLineage(lineage, result); writeSseChunk(response, buildChunkPayload(completionId, requestOptions.model.id, {}, parsed.toolCalls.length ? "tool_calls" : "stop")); response.end("data: [DONE]\n\n"); return;
    } catch (error) { if (error?.code === "INVALID_CHAT_SESSION" && lineage?.sessionId && !retryInvalidSession) { onInvalidSession?.(); return streamOpenAiResponse({ ...options, lineage: { ...lineage, sessionId: null, parentMessageId: null }, retryInvalidSession: true }); } beginSse(response); writeSseError(response, error); response.end("data: [DONE]\n\n"); return; }
  }
  const toolSieve = requestOptions.toolNames.length ? createToolSieve(requestOptions.toolNames) : null; const transcriptRouter = createTranscriptLeakRouter(); let toolCallIndex = 0; let sawToolCall = false; let emittedImageGeneration = false; let lastRoutedKind = "response"; let emittedOutput = false;
  beginSse(response); writeSseChunk(response, buildChunkPayload(completionId, requestOptions.model.id, { role: "assistant" }));
  const emitReasoningText = (text) => { if (text) { emittedOutput = true; writeSseChunk(response, buildChunkPayload(completionId, requestOptions.model.id, { reasoning_content: text })); } }; const reasoningRedactor = createStreamingReasoningRedactor(emitReasoningText); const emitPlainText = (kind, text) => { if (!text) return; if (kind === "thinking") { reasoningRedactor.push(text); return; } emittedOutput = true; reasoningRedactor.flush(); writeSseChunk(response, buildChunkPayload(completionId, requestOptions.model.id, { content: text })); }; const emitRoutedText = (kind, text) => { if (kind === "thinking") { emitPlainText(kind, text); return; } transcriptRouter.push(text).forEach((event) => emitPlainText(event.kind, event.text)); };
  const emitToolCalls = (calls) => { const repaired = repairToolCalls({ calls: limitImageGenerationCalls(calls), tools: requestOptions.tools, messages: requestOptions.messages }); let filtered = repaired.calls; if (emittedImageGeneration) filtered = filtered.filter((call) => !IMAGE_GENERATION_TOOL_NAMES.has(call.name)); const rejectionText = formatRejectedToolCalls(repaired.rejected); if (rejectionText) emitPlainText("response", rejectionText); if (!filtered.length) return; if (filtered.some((call) => IMAGE_GENERATION_TOOL_NAMES.has(call.name))) emittedImageGeneration = true; sawToolCall = true; emittedOutput = true; writeSseChunk(response, buildChunkPayload(completionId, requestOptions.model.id, { tool_calls: createChatToolCalls(filtered, toolCallIndex) })); toolCallIndex += filtered.length; };
  const routeToolAwareText = (kind, text) => { if (!text) return; lastRoutedKind = kind; if (!toolSieve) { emitRoutedText(kind, text); return; } toolSieve.push(text).forEach((event) => { if (event.type === "tool_calls") emitToolCalls(event.calls ?? []); else if (event.text) emitRoutedText(kind, event.text); }); };
  try { const result = await streamCompletionContent({ account, deleteAfterFinish, onDelta: (delta) => routeToolAwareText(delta.kind, delta.text), requestOptions }); routeToolAwareText("response", formatSearchSources(result.searchResults)); if (toolSieve) toolSieve.flush().forEach((event) => { if (event.type === "tool_calls") emitToolCalls(event.calls ?? []); else if (event.text) emitRoutedText(lastRoutedKind, event.text); }); rememberLineage(lineage, result); transcriptRouter.flush().forEach((event) => emitPlainText(event.kind, event.text)); reasoningRedactor.flush(); writeSseChunk(response, buildChunkPayload(completionId, requestOptions.model.id, {}, sawToolCall ? "tool_calls" : "stop")); } catch (error) { if (error?.code === "INVALID_CHAT_SESSION" && lineage?.sessionId && !retryInvalidSession && !emittedOutput) { onInvalidSession?.(); return streamOpenAiResponse({ ...options, lineage: { ...lineage, sessionId: null, parentMessageId: null }, retryInvalidSession: true }); } writeSseError(response, error); }
  response.end("data: [DONE]\n\n");
}
