import { AsyncLocalStorage } from "node:async_hooks";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { config } from "../config.js";
const STORE_KEY = process.env.APP_REDIS_STORE_KEY || "deepseek2api:app-state:v1";
const storeContext = new AsyncLocalStorage();
function defaultState() { return { accounts: [], apiKeys: [], incognito: { globalEnabled: false, owners: {} }, invites: [], registration: { inviteRequired: false }, sessions: [], sharedAccountMode: { enabled: false }, systemSettings: { captcha: {} }, users: [] }; }
function normalizeIncognito(value) { return { globalEnabled: Boolean(value?.globalEnabled), owners: value?.owners && typeof value.owners === "object" ? value.owners : {} }; }
function normalizeInvites(value) { return Array.isArray(value) ? value : []; }
function normalizeRegistration(value) { return { inviteRequired: Boolean(value?.inviteRequired) }; }
function normalizeSharedAccountMode(value, incognito, accounts) { return { enabled: Boolean(value?.enabled && incognito.globalEnabled && accounts.some((account) => account?.id && account?.token)) }; }
function normalizeNumber(value, fallback, { min = 0, max = Number.MAX_SAFE_INTEGER } = {}) { const parsed = Number(value); return Number.isFinite(parsed) ? Math.max(min, Math.min(max, Math.trunc(parsed))) : fallback; }
function normalizeSystemSettings(value) { const captcha = value?.captcha && typeof value.captcha === "object" ? value.captcha : {}; return { captcha: { yescaptchaEndpoint: typeof captcha.yescaptchaEndpoint === "string" ? captcha.yescaptchaEndpoint : "", yescaptchaKey: typeof captcha.yescaptchaKey === "string" ? captcha.yescaptchaKey : "", autoSolveEnabled: captcha.autoSolveEnabled === undefined ? undefined : Boolean(captcha.autoSolveEnabled), visionFallbackEnabled: captcha.visionFallbackEnabled === undefined ? undefined : Boolean(captcha.visionFallbackEnabled), visionFallbackAccountId: typeof captcha.visionFallbackAccountId === "string" ? captcha.visionFallbackAccountId : null, maxRetries: captcha.maxRetries === undefined ? undefined : normalizeNumber(captcha.maxRetries, undefined, { min: 1, max: 20 }), cooldownMs: captcha.cooldownMs === undefined ? undefined : normalizeNumber(captcha.cooldownMs, undefined, { min: 0, max: 3600000 }) } }; }
function normalizeUsers(value) { const normalizeLimit = (limit) => { const parsed = Number(limit); return Number.isInteger(parsed) && parsed > 0 ? parsed : null; }; return Array.isArray(value) ? value.map((user) => ({ ...user, disabled: Boolean(user?.disabled), requestLimits: { maxConcurrency: normalizeLimit(user?.requestLimits?.maxConcurrency), maxRequestsPerMinute: normalizeLimit(user?.requestLimits?.maxRequestsPerMinute) } })) : []; }
function normalizeApiKeys(value) { return Array.isArray(value) ? value.map((record) => ({ ...record, toolCallsEnabled: Boolean(record?.toolCallsEnabled), accountMode: record?.accountMode === "round_robin" ? "round_robin" : "fixed" })) : []; }
function normalizeState(value) { const incognito = normalizeIncognito(value?.incognito); const accounts = Array.isArray(value?.accounts) ? value.accounts : []; return { accounts, apiKeys: normalizeApiKeys(value?.apiKeys), incognito, invites: normalizeInvites(value?.invites), registration: normalizeRegistration(value?.registration), sessions: Array.isArray(value?.sessions) ? value.sessions : [], sharedAccountMode: normalizeSharedAccountMode(value?.sharedAccountMode, incognito, accounts), systemSettings: normalizeSystemSettings(value?.systemSettings), users: normalizeUsers(value?.users) }; }
function resolveRedisConfig() { const url = process.env.UPSTASH_REDIS_REST_URL || process.env.KV_REST_API_URL || process.env.REDIS_REST_URL || ""; const token = process.env.UPSTASH_REDIS_REST_TOKEN || process.env.KV_REST_API_TOKEN || process.env.REDIS_REST_TOKEN || ""; return url && token ? { url: url.replace(/\/$/, ""), token } : null; }
async function executeRedis(command) { const redis = resolveRedisConfig(); if (!redis) { if (process.env.VERCEL) throw new Error("Upstash Redis environment variables are missing"); return null; } const response = await fetch(redis.url, { method: "POST", headers: { authorization: `Bearer ${redis.token}`, "content-type": "application/json" }, body: JSON.stringify(command) }); if (!response.ok) throw new Error(`Upstash Redis request failed (HTTP ${response.status})`); const payload = await response.json(); if (payload.error) throw new Error(`Upstash Redis error: ${payload.error}`); return payload.result; }
function readLocalStore() { if (!existsSync(config.dataFile)) { const state = defaultState(); writeFileSync(config.dataFile, JSON.stringify(state, null, 2)); return state; } return normalizeState(JSON.parse(readFileSync(config.dataFile, "utf8"))); }
function writeLocalStore(state) { writeFileSync(config.dataFile, JSON.stringify(normalizeState(state), null, 2)); }
async function loadRequestState() { if (!resolveRedisConfig()) { if (process.env.VERCEL) throw new Error("Upstash Redis environment variables are missing"); return readLocalStore(); } const stored = await executeRedis(["GET", STORE_KEY]); return stored ? normalizeState(typeof stored === "string" ? JSON.parse(stored) : stored) : defaultState(); }
async function persistRequestState(state) { const normalized = normalizeState(state); if (!resolveRedisConfig()) { if (process.env.VERCEL) throw new Error("Upstash Redis environment variables are missing"); writeLocalStore(normalized); return; } await executeRedis(["SET", STORE_KEY, JSON.stringify(normalized)]); }
export async function runWithStore(callback) { const context = { dirty: false, state: await loadRequestState() }; return storeContext.run(context, async () => { try { return await callback(); } finally { if (context.dirty) await persistRequestState(context.state); } }); }
export function readStore() { const context = storeContext.getStore(); return context ? context.state : readLocalStore(); }
export function writeStore(state) { const context = storeContext.getStore(); if (context) { context.state = normalizeState(state); context.dirty = true; return; } if (process.env.VERCEL) throw new Error("Persistent store write attempted outside a request context"); writeLocalStore(state); }
export function updateStore(updater) { const next = updater(readStore()); writeStore(next); return normalizeState(next); }
